# Generated by Django 6.0.6 on 2026-07-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphoto',
            name='uploaded_at',
        ),
    ]
